uploads = []
generated = []

[[outputs]]
id = "YeK-LTw_c3PBThPoPXtOV"
uri = "file://bot.py"
type = "unspecified"
title = "bot.py"

[[outputs]]
id = "2pEEVi1HTjHj0LvdBu5XF"
uri = "file://bot_py.zip"
type = "unspecified"
title = "bot.py"
